frontendConfig:
  availableNamespace:
    {{- toYaml .Values.frontendConfig.availableNamespace | nindent 4 }}
  availableCluster:
    {{- toYaml .Values.frontendConfig.availableCluster | nindent 4 }}
  availableDestinationSvc:
    {{- toYaml .Values.frontendConfig.availableDestinationSvc | nindent 4 }}

istioRedirectorConfig:
  server:
    URL: {{ .Values.istioRedirectorConfig.server.URL }}
    allowedOrigins:
      {{- toYaml .Values.istioRedirectorConfig.server.allowedOrigins | nindent 4 }}
  istio:
    gateways:
      {{- toYaml .Values.istioRedirectorConfig.istio.gateways | nindent 4 }}

github:
  {{- toYaml .Values.github | nindent 2 }}