server:
  URL: {{ .Values.istioRedirectorConfig.server.URL }}
  allowedOrigins:
    {{- toYaml .Values.istioRedirectorConfig.server.allowedOrigins | nindent 4 }}

frontendConfig:
  availableNamespace:
    {{- toYaml .Values.frontendConfig.availableNamespace | nindent 4 }}
  availableCluster:
    {{- toYaml .Values.frontendConfig.availableCluster | nindent 4 }}

istio:
  {{- toYaml .Values.istioRedirectorConfig.istio | nindent 2 }}

github:
  token: {{ .Values.github.token }}
  email: {{ .Values.github.email }}
  owner: {{ .Values.github.owner }}
  repo: {{ .Values.github.repo }}
  baseRef: {{ .Values.github.baseRef }}
  newBranchPrefix: {{ .Values.github.newBranchPrefix }}