server:
{{- toYaml .Values.server | nindent 4 }}

istio:
{{- toYaml .Values.istio | nindent 4 }}

frontendConfig:
{{- toYaml .Values.frontendConfig | nindent 4 }}

github:
{{- toYaml .Values.github | nindent 4 }}