name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ env.GIT_TAG }}
      run: docker build . --file Dockerfile --tag etifontaine/istio-redirector:$IMAGE_TAG

    - name: Docker Push
      env:
        IMAGE_TAG: ${{ env.GIT_TAG }}
      run: docker push etifontaine/istio-redirector:$IMAGE_TAG